### PR TITLE
Deploy contract from custom account

### PR DESCRIPTION
**Pull request by delaaxe**
Contracts can be deployed by custom accounts on zkSync, however the typing of the Deployer class doesn't allow it without using `any`.

This is a draft in order gauge the level of interest in this. The typing is complex in order to keep backwards compatibility, however with breaking changes it could be simplified.

### CODE REVIEW

**Comment by mpavlovic-txfusion** [comment]
> Contracts can be deployed by custom accounts on zkSync, however the typing of the Deployer class doesn't allow it without using `any`.
> 
> This is a draft in order gauge the level of interest in this. The typing is complex in order to keep backwards compatibility, however with breaking changes it could be simplified.

Hi @delaaxe, can you provide an example of the script that is using this suggested Deployer implementation to deploy some contract by custom account? 
Because it looks to me that currently, using Account Abstraction contracts to deploy other contracts is not supported by the Deployer class regardless of the typing...

**Comment by mpavlovic-txfusion** [comment]
@delaaxe Considering that this is a hardhat plugin for zkSync, it should be used inside of the Hardhat (Node.js) environment, so it doesn't seem to be relevant to support the `zk.Signer` class which should be used from the browser environment and initiated through `Web3Provider.getSigner()` that accept the `ExternalProvider` instance injected by some browser wallet like Metamask (example can be seen here [zk.Signer](https://era.zksync.io/docs/api/js/accounts.html#signer)).

**Comment by delaaxe** [comment]
Scenario:

- You own a `TwoUserMultisig` custom account as explained here: https://github.com/matter-labs/custom-aa-tutorial
- This account require 2 signatures in `TransactionRequest.customData.customSignature`, so you can implement a custom `Signer` to send transactions from this account which does something like [this](https://github.com/matter-labs/custom-aa-tutorial/blob/main/deploy/deploy-multisig.ts#L75-L85).
- Then, sending regular transactions from this account works fine like so:
```typescript
const customSigner = new SignerForTwoUserMultisig(multisigAddress, owner1, owner2);
const dapp = new zksync.Contract(address, abi, customSigner);
const response = await dapp.swap(...); 
```
- Now you want to deploy a smart contract from this custom account (not from an EOA or from one of the owners of the custom account). Deployment works differently on zkSync with the Deployer class, but that class won't accept my custom Signer (although it almost works if you ignore type errors).
- Currently we're using a workaround like this, but deploying from custom account should be supported by the SDK seamlessly ("account abstraction" includes "deployment abstraction"):
```typescript
// Temporary hack while waiting for `hardhat-zksync-deploy` to be updated
export class CustomDeployer extends Deployer {
  constructor(signer: ethers.Signer & { provider: ethers.providers.Provider }) {
    super(hre, zksync.Wallet.createRandom()); // random wallet because overwritten below
    this.zkWallet = signer.connect(signer.provider) as any;  // no connectToL1
  }

  public async estimateDeployGas(artifact: ZkSyncArtifact, constructorArguments: any[]): Promise<ethers.BigNumber> {
    const factoryDeps = await this.extractFactoryDeps(artifact);
    const factory = new zksync.ContractFactory(artifact.abi, artifact.bytecode, this.zkWallet);

    const deployTx = factory.getDeployTransaction(...constructorArguments, {
      customData: {
        factoryDeps,
      },
    });
    deployTx.from = await this.zkWallet.getAddress(); // using `getAddress` instead of `.address`

    return await this.zkWallet.provider.estimateGas(deployTx);
  }
}
```

**Comment by nikola-bozin-txfusion** [comment]
Thank you @delaaxe . There has been much discussion about how to simplify this process, and our SDK team is currently working on developing a more user-friendly interface. Consequently, we are closing this issue.

**Pull request closed without merging**
