### PR TITLE
Download zksolc binaries automatically

### PR DESCRIPTION
**Pull request by ly0va**

### CODE REVIEW

**Review by popzxc — APPROVED** [review]

**Comment by wong2** [comment]
> 2. [Hardhat compiler plugin](https://github.com/matter-labs/hardhat-zksync) is now able to download compiler binaries instead of Docker images.

Hi, have you forgot to release this to npm?

**Comment by popzxc** [comment]
@wong2 indeed, it seems so. Sorry for that! We'll publish it soon.

**Comment by popzxc** [comment]
@wong2 new versions are published (for solc it's 0.3.7 and for vyper it's 0.1.1)

**Comment by wong2** [comment]
thx

**Comment by ly0va** [comment]
@wong2 Currently only Linux binaries are available to download.
MacOS ones should be published within a week.
While you wait, you can try and use dockerized zksolc.

**Comment by wong2** [comment]
OK, thanks.

**Pull request merged**
